### ISSUE TITLE
Ownership.

### ISSUE THREAD

**Issue by jfjlaros** [LUMC/kPAL#11]
Hi @martijnvermaat I hope you are doing well.

Could you add me as one of the owners of this project? Thank you in advance.

**Comment by martijnvermaat** [comment]
Hi @jfjlaros , I'm doing well and hope you are too :)

It seems that I'm not an owner of this project either, so don't have access to the project settings. I also can't see who does.

**Comment by jfjlaros** [comment]
Yes, everything is fine here too. Thanks.

This is pretty strange if you ask me. Perhaps I have to contact one of the owners of the LUMC organization then.

**Comment by jfjlaros** [comment]
Yes, I have full access now. You got an invitation to join.
